# Generated by Django 2.0 on 2017-12-11 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171203_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyprofile',
            options={'verbose_name': 'Профиль семьи', 'verbose_name_plural': 'Профили семей'},
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
