# Generated by Django 2.0 on 2017-12-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20171211_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('STAFF', 'Сотрудник'), ('FAMILY', 'Семья'), ('BENEFACTOR', 'Благотворитель')], default='BENEFACTOR', max_length=15)),
                ('position', models.CharField(max_length=30, verbose_name='Позиция')),
                ('trips_per_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Необходимое количество поездок в месяц')),
                ('car_requirements', models.TextField(blank=True, verbose_name='Требования к машине')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='Дополнительно')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='familyprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FamilyProfile',
        ),
    ]
