# Generated by Django 2.0rc1 on 2017-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=140)),
                ('arrival', models.CharField(max_length=140)),
                ('purpose', models.CharField(max_length=420)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('created', models.DateTimeField()),
                ('status', models.CharField(choices=[('CR', 'Создана'), ('AP', 'На модерации'), ('AC', 'Принята'), ('DE', 'Отклонена'), ('CL', 'Завершена')], default='CR', max_length=2)),
                ('length', models.FloatField()),
            ],
        ),
    ]
