# Generated by Django 2.0rc1 on 2017-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival',
            field=models.CharField(max_length=140, verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время возврата'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(verbose_name='Дата поездки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.CharField(max_length=140, verbose_name='Пункт отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина пути'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='purpose',
            field=models.CharField(max_length=420, verbose_name='Цель поездки'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('CR', 'Создана'), ('AP', 'На модерации'), ('AC', 'Принята'), ('DE', 'Отклонена'), ('CO', 'Завершена')], default='CR', max_length=2, verbose_name='Статус'),
        ),
    ]
